<?php

namespace application\admin\controller;


use application\admin\model\SrsApi;

/**
 * Class ApiController
 * @package application\admin\controller
 * @property SrsApi $_srsApi
 */
class ApiController extends BaseController
{
	protected $_srsApi = null;

	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->_srsApi = new SrsApi("192.168.1.120", 1985);
	}

	public function Index(string $b_name = "")
	{
		$data = $this->_srsApi->Index($b_name);
		$this->R(null, null, $data);
	}

	public function Vhosts(int $vhost_id = null)
	{
		$data = $this->_srsApi->Vhosts($vhost_id);

		$this->R(null, $data);
	}

	public function Streams(int $stream_id = null)
	{
		$data = $this->_srsApi->Streams($stream_id);

		$this->R(null, $data);
	}

	public function ClientList(int $page = 1, int $page_size = 20)
	{
		$data = $this->_srsApi->ClientList($page, $page_size);

		$this->R(null, $data);
	}

	public function ClientInfo(int $client_id)
	{
		$data = $this->_srsApi->ClientInfo($client_id);

		$this->R(null, $data);
	}

	public function Summaries()
	{
		$data = $this->_srsApi->Summaries();

		$this->R(null, $data);
	}

	public function MemInfos()
	{
		$data = $this->_srsApi->MemInfos();

		$this->R(null, $data);
	}

	public function SystemProcStats()
	{
		$data = $this->_srsApi->SystemProcStats();

		$this->R(null, $data);
	}

	public function SelfProcStats()
	{
		$data = $this->_srsApi->SelfProcStats();

		$this->R(null, $data);
	}

	public function Rusages()
	{
		$data = $this->_srsApi->Rusages();

		$this->R(null, $data);
	}

}
